jobs:
  - job: CI_Job
    displayName: Unit and Integration Tests (CI)
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: 'test'
        configuration: 'debug'
        projects: 'DemoWebsiteTests\DemoWebsiteTests.csproj'

  - job: CD_Environment_Job
    displayName: Deploy environment
    dependsOn: CI_Job
    pool:
      vmImage: 'windows-latest'