jobs:
  - job: CI_Job
    displayName: Unit and Integration Tests (CI)
    pool:
      vmImage: 'windows-latest'

    steps:
    # Add this Command to Include the .NET 6 SDK
    - task: UseDotNet@2
      displayName: Use .NET 6.0
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
           
    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: 'test'
        configuration: 'debug'
        projects: 'DemoWebsiteTests\DemoWebsiteTests.csproj'

  - job: CD_Environment_Job
    displayName: Deploy environment
    dependsOn: CI_Job
    pool:
      vmImage: 'windows-latest'