on: push

jobs:
  setup:
    name: Choose Secrets Environment Job
    runs-on: windows-latest
    steps:
      - id: setup
        name: Setup Environment Setp
        run: |
            if ('${{ github.ref }}' -eq 'refs/heads/main') { 
              echo "::set-output name=build_env::prod"
            } else {
              echo "::set-output name=build_env::dev"
            }
    outputs:
      build_env: ${{ steps.setup.outputs.build_env }}

  build_deploy:
    name: Build and Deploy
    needs: setup
    environment: ${{ needs.setup.outputs.build_env }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - id: integrationtest
        name: Integration Tests
        run: |
            $unitTestFilePath = "${{ env.RUNNER_TEMP }}\TestResults\unittests.xml"
            Push-Location .\DemoWebsiteTests\
            dotnet test --logger "junit;LogFilePath=$unitTestFilePath"

      - name: Publish test results
        if: ${{ always() }}
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        with:
          files: ${{ env.RUNNER_TEMP }}/TestResults/*.xml

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MS_AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - id: buid-and-deploy
        name: Build Azure environment
        run: |
          .\Deployment\Build.ps1 -LOCATION ${{ secrets.LOCATION }} `
            -BUILD_ENV ${{ needs.setup.outputs.build_env }} `
            -RESOURCE_GROUP ${{ secrets.RESOURCE_GROUP }} `
            -PREFIX ${{ secrets.PREFIX }} `
            -GITHUB_REF ${{ github.ref }}